name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 12 * * *'

jobs:
  test:
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: test
        run: make test ABI3AUDIT_EXTRA=test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: lint
        run: make lint PIP_AUDIT_EXTRA=lint

  check-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: python -m pip install .

      - name: check-readme
        run: |
          diff \
            <( \
              awk '/@begin-abi3audit-help@/{f=1;next} /@end-abi3audit-help@/{f=0} f' \
                < README.md | sed '1d;$d' \
            ) \
            <( \
              python -m abi3audit --help \
            )
