on:
  release:
    types:
      - published

name: release

permissions: {} # All jobs define their needed permissions below.

jobs:
  build:
    name: Build distributions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0

      - name: Build distributions
        run: make dist

      - name: Store distributions
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: python-package-distributions
          path: dist/

  publish:
    name: upload distributions to PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Used to authenticate to PyPI via OIDC.

    steps:
      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: false

      - name: Download distributions
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: python-package-distributions
          path: dist/

      - uses: astral-sh/attest-action@f35111fb79f1e4f0150a1ee16cfd4399e3151bdb # v0.0.5

      - name: publish
        run: uv publish --trusted-publishing=always
