name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: test
        run: cargo test

  all-tests-pass:
    name: All tests pass
    if: always()
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: check test jobs
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
